### PR TITLE
Fix CMake build on Apple Silicon

### PR DESCRIPTION
**Pull request by madebr**
On Apple silicon, `cmake_host_system_information(RESULT HAVE_FPU QUERY HAS_FPU)` returns `HAVE_FPU=0`.
I reported this [upstream](https://gitlab.kitware.com/cmake/cmake/-/issues/25950).

Without a detected fpu, the build fails when `REAL_IS_FIXED` is defined, and neon is detected.
https://github.com/madebr/mpg123/actions/runs/8916112597/job/24486953667#step:5:13

My fix moves the cpu arch detection earlier, and hard enables `HAVE_FPU` for apple arm64.

As an extra, I added a patch that adds macos CI.

### CODE REVIEW

**Comment by sobukus** [comment]
Applied to svn, thanks. I don't consider this something urgent, though, as you can build mpg123 on Mac just fine using autotools (right?). Maybe we should have a CI target for that, too.

**Comment by madebr** [comment]
> Applied to svn, thanks. I don't consider this something urgent, though, as you can build mpg123 on Mac just fine using autotools (right?). Maybe we should have a CI target for that, too.

Yeah, autotools builds fine.
At least, homebrew users haven't noticed a break. I'll add autotools to the macos yml.

**Comment by sobukus** [comment]
So … finished here?

**Comment by madebr** [comment]
Closing

**Pull request closed without merging**
